// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';

@immutable
class UserDTO extends Equatable {
  const UserDTO({
    required this.id,
    required this.email,
    required this.name,
    required this.role,
    required this.avatar,
    required this.creationAt,
    required this.updatedAt,
  });

  final int id;
  final String email;
  final String name;
  final String role;
  final String avatar;
  final String creationAt;
  final String updatedAt;

  static List<UserDTO> fromJsonList(List<dynamic> jsonList) => jsonList
      .map((json) => UserDTO.fromMap(json as Map<String, dynamic>))
      .toList();

  @override
  List<Object> get props {
    return [
      id,
      email,
      name,
      role,
      avatar,
      creationAt,
      updatedAt,
    ];
  }

  UserDTO copyWith({
    int? id,
    String? email,
    String? name,
    String? role,
    String? avatar,
    String? creationAt,
    String? updatedAt,
  }) {
    return UserDTO(
      id: id ?? this.id,
      email: email ?? this.email,
      name: name ?? this.name,
      role: role ?? this.role,
      avatar: avatar ?? this.avatar,
      creationAt: creationAt ?? this.creationAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'email': email,
      'name': name,
      'role': role,
      'avatar': avatar,
      'creation_at': creationAt,
      'updated_at': updatedAt,
    };
  }

  factory UserDTO.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return UserDTO(
      id: cast<num>('id').toInt(),
      email: cast<String>('email'),
      name: cast<String>('name'),
      role: cast<String>('role'),
      avatar: cast<String>('avatar'),
      creationAt: cast<String>('creation_at'),
      updatedAt: cast<String>('updated_at'),
    );
  }

  @override
  String toString() {
    return 'UserDTO(id: $id, email: $email, name: $name, role: $role, avatar: $avatar, creationAt: $creationAt, updatedAt: $updatedAt)';
  }

  String toJson() => json.encode(toMap());

  factory UserDTO.fromJson(String source) =>
      UserDTO.fromMap(json.decode(source) as Map<String, dynamic>);
}
