name: ui
description: Design system — themes, text styles, and reusable widgets.
version: 0.0.1
publish_to: "none"
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  auto_size_text: ^3.0.0
  gap: ^3.0.1
  iconsax_plus: ^1.0.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
