name: "Code Analysis"

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: Get Flutter Version From FVM config
        id: get_flutter_version
        run: echo "version=$(jq -r '.flutter' .fvmrc)" >> "$GITHUB_OUTPUT"

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get_flutter_version.outputs.version }}
          channel: stable
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🦄 Generate Code
        run: |
          flutter gen-l10n
          dart run build_runner build --delete-conflicting-outputs

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed .

      - name: 🕵️ Analyze
        run: flutter analyze .

      - name: 🧪 Run Tests
        run: flutter test --coverage --coverage-path=coverage/lcov.info --test-randomize-ordering-seed=random --concurrency=10
